const mongoose=require("mongoose");
const User = require("../models/user");

const connectionRequestSchema=new mongoose.Schema({
    fromUserId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:User
    },
    toUserId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true
    },
    status:{
        type:String,
        enum:{
            values:["ignore","interested","accepted","rejected"],
            message:`{value} is not a valid status type`
        },
    }
},
{
    timestamps:true,
}
);

connectionRequestSchema.index({fromUserId:1,toUserId:1});

//database validation user cannot send a req to himself
//it will be called everytime before connection req saved 
connectionRequestSchema.pre("save",function(next){//save is event handler
    const connectionRequest=this;

    //check if the fromuserid is same as touserid
    if(connectionRequest.fromUserId.equals(connectionRequest.toUserId)){
        throw new Error("cannot send connection req to yourself")
    }
    next();
})

const ConnectionRequestModel=new mongoose.model(
    "ConnectionRequest",
    connectionRequestSchema
);

module.exports=ConnectionRequestModel;




//mongoose.Schema.Types.ObjectId DEFINITION
// mongoose.Schema.Types.ObjectId is a special data type in Mongoose that 
// represents a MongoDB ObjectId — the unique _id value automatically 
// generated by MongoDB for every document.


//ENUM DEFINITION
// In Mongoose, enum is short for enumeration — it defines a list of allowed values for a field.
// If you try to save anything outside that list, Mongoose will throw a validation error.



// Arguments passed into mongoose.model()
// mongoose.model() takes two main arguments:
// Model Name (String)
// "ConnectionRequest"
// This is the singular name for the collection.
// Mongoose automatically converts this to a plural, lowercase collection name → connectionrequests.
// Schema Object
// connectionRequestSchema
// This is the structure/blueprint that defines what fields exist in the documents.